---
name: build push and deploy to ecs
on:
  workflow_dispatch:
    inputs:
      path:
        description: Path to the application
        required: false
        default: .
      tag:
        description: Docker image tag
        required: false
        default: latest
      ecr_repo:
        description: ECR Repository name
        required: false
        default: nginx/vishnu
env:
  ecr_repo: ${{ github.event.inputs.ecr_repo }}
  aws_region: us-east-2
  path: ${{ github.event.inputs.path }}
  tag: ${{ github.event.inputs.tag }}
  ecs_service: ecs-demo-wordpress-service-vishnu
  ecs_cluster: ECS-demo
jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_DEPLOYER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_DEPLOYER }}
          aws-region: ${{ env.aws_region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ecr_registry: ${{ steps.login-ecr.outputs.registry }}
        run: >
          cd ${{ env.path }}

          docker build -t ${{ env.ecr_registry }}/${{ env.ecr_repo }}:${{ env.tag }} .

          docker push ${{ env.ecr_registry }}/${{ env.ecr_repo }}:${{ env.tag }}

          echo "image=${{ env.ecr_registry }}/${{ env.ecr_repo }}:${{ env.tag }}" >> $GITHUB_OUTPUT
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ecs-demo-wordpress
          image: ${{ steps.build-image.outputs.image }}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ecs_service }}
          cluster: ${{ env.ecs_cluster }}
          wait-for-service-stability: true

